# Generated by Django 4.2.10 on 2024-05-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Grouping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='home.grouping'),
        ),
    ]
