# Generated by Django 4.2.10 on 2024-04-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_author_users_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_users',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
