# Generated by Django 4.2.10 on 2024-05-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact_us',
            old_name='Location',
            new_name='location',
        ),
    ]
