# Generated by Django 4.2.10 on 2024-04-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_author_alter_post_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_add_post', 'Can add post'), ('can_change_post', 'Can change post'), ('can_delete_post', 'Can delete post')]},
        ),
    ]
